import Navigator from "@/components/Navigator/Navigator";
import "./globals.css";
import styles from "./page.module.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Inter } from "next/font/google";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-mono">
      <body className="overflow-hidden w-full h-full relative">
        <nav className="hidden md:fixed md:inset-y-0 md:flex md:w-52 md:flex-col bg-neutral-800">
          <Navigator />
        </nav>
        <main className="flex flex-1 flex-col md:pl-52 h-full bg-zinc-700">
          {children}
        </main>
      </body>
    </html>
  );
}
